config/routes.rb
Rails.application.routes.draw do
  root 'captain_combat#show'

  resources :fighters
  resources :fights, only: [:new, :create, :show, :index]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/fight.rb
class Fight < ApplicationRecord
  has_one :fighter_one, class_name: 'Fighter', foreign_key: 'fighter_one_id'
  has_one :fighter_two, class_name: 'Fighter', foreign_key: 'fighter_two_id'

  validate :not_the_same_fighter

  def not_the_same_fighter
      errors.add(:fight, "can't have a fighter fiightting against himself") if fighter_one_id == fighter_two_id
  end

  private
  
  def self.fight_between(f_one, f_two)
    ### Fighter One ###
    f1 = Fighter.find(f_one[:fighter_id])
    # w1 = Figher.find(f_one[:fighter_id])
    # s1 = Figher.find(f_one[:fighter_id])

    stats_one = {
      life: f1.life, # + s1.type == 'life' ? s1.stat : 0,
      attack: f1.attack, # + w1.type == 'attack' ? w1.stat,
      dodge: f1.dodge, # + s1.type == 'dodge' ? s1.stat : 0,
      critical: f1.critical # +w1.type == 'critical' ? w1.stat : 0
    }

    ### Fighter Two ###
    f2 = Fighter.find(f_two[:fighter_id])
    # w2 = Figher.find(f_one[:fighter_id])
    # s2 = Figher.find(f_one[:fighter_id])

    stats_two = {
      life: f2.life, # + s2.type == 'life' ? s2.stat : 0,
      attack: f2.attack, # + w2.type == 'attack' ? w2.stat,
      dodge: f2.dodge, # + s2.type == 'dodge' ? s2.stat : 0,
      critical: f2.critical # +w2.type == 'critical' ? w2.stat : 0
    }

    ### Create Fight Result and History
    r = Random.new
    history = "Fight Between #{f1.name} and #{f2.name}"
    while (stats_one[:life] > 0 && stats_two[:life] > 0)
      ## Fighter One Turn
      ad = stats_one[:attack]
      history += "|#{f1.name} is attacking for #{ad} damage!"

      if (r.rand(0..100) <= stats_one[:critical])
        ad *= 2
        history += "|It's a critical hit ! It'll deal double damage (#{ad})"
      end

      if (r.rand(0..100) <= stats_two[:dodge])
        history += "|#{f2.name} dodges the attack with a magnificent sidestep !"
      else
        stats_two[:life] -= ad
        history += "|#{f2.name} suffers the loss of #{ad} life points !"
      end

      break if stats_two[:life] <= 0

      ## Fighter One Turn
      ad = stats_two[:attack]
      history += "|#{f2.name} is attacking for #{ad} damage!"

      if (r.rand(0..100) <= stats_two[:critical])
        ad *= 2
        history += "|It's a critical hit ! It'll deal double damage (#{ad})"
      end

      if (r.rand(0..100) <= stats_two[:dodge])
        history += "|#{f1.name} dodges the attack with a magnificent sidestep !"
      else
        stats_one[:life] -= ad
        history += "|#{f1.name} suffers the loss of #{ad} life points !"
      end
    end

    history += "|The fight is over ! Congratulation to our two fighters : #{f1.name} and #{f2.name}"

    if stats_one[:life] <= 0
      winner = f2
      looser = f1
    else
      winner = f1
      looser = f2
    end

    history += "|And the winner is... #{winner.name} !!"

    return {
      winner_id: winner.id,
      looser_id: looser.id,
      history: history,
      fighter_one_id: f1.id,
      fighter_two_id: f2.id
    }
  end
end

app/models/fighter.rb
class Fighter < ApplicationRecord
  validates :name, presence: true
  validates :life, :attack, :dodge, :critical, inclusion:
    { in: 0..10, message: "can't have less than 0 or more than 10 skillpoints" }

  validate :cant_have_more_than_15_skillpoints

  def cant_have_more_than_15_skillpoints
    skillpoints = life + attack + dodge + critical
    if skillpoints > 15
      errors.add(:fighter, "can't have more than 15 skillpoints, current: #{skillpoints}")
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/captain_combat_controller.rb
class CaptainCombatController < ApplicationController
	def show
  end
end

app/controllers/fighters_controller.rb
class FightersController < ApplicationController
  before_action :set_fighter, only: [:show, :edit, :update, :destroy]

  # GET /fighters
  # GET /fighters.json
  def index
    @fighters = Fighter.all
  end

  # GET /fighters/1
  # GET /fighters/1.json
  def show
  end

  # GET /fighters/new
  def new
    @fighter = Fighter.new
  end

  # GET /fighters/1/edit
  def edit
  end

  # POST /fighters
  # POST /fighters.json
  def create
    @fighter = Fighter.new(fighter_params)

    respond_to do |format|
      if @fighter.save
        format.html { redirect_to @fighter, notice: 'Fighter was successfully created.' }
        format.json { render :show, status: :created, location: @fighter }
      else
        format.html { render :new }
        format.json { render json: @fighter.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /fighters/1
  # PATCH/PUT /fighters/1.json
  def update
    respond_to do |format|
      if @fighter.update(fighter_params)
        format.html { redirect_to @fighter, notice: 'Fighter was successfully updated.' }
        format.json { render :show, status: :ok, location: @fighter }
      else
        format.html { render :edit }
        format.json { render json: @fighter.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /fighters/1
  # DELETE /fighters/1.json
  def destroy
    @fighter.destroy
    respond_to do |format|
      format.html { redirect_to fighters_url, notice: 'Fighter was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_fighter
      @fighter = Fighter.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def fighter_params
      params.require(:fighter).permit(:name, :life, :attack, :dodge, :critical, :bio)
    end
end

app/controllers/fights_controller.rb
class FightsController < ApplicationController
  before_action :set_fight, only: :show

  # GET /fights
  # GET /fights.json
  def index
    @fights = Fight.all
  end

  # GET /fights/1
  # GET /fights/1.json
  def show
    @winner = Fighter.find(@fight.winner_id)
    @looser = Fighter.find(@fight.looser_id)
  end

  # GET /fights/new
  def new
    @fighters = Fighter.all
    @fight = Fight.new
  end

  # POST /fights
  # POST /fights.json
  def create
    @fighters = Fighter.all
    @fight = Fight.create(Fight.fight_between(params[:one], params[:two]))

    respond_to do |format|
      if @fight.save
        format.html { redirect_to @fight, notice: 'Fight was successfully created.' }
        format.json { render :show, status: :created, location: @fight }
      else
        format.html { render :new }
        format.json { render json: @fight.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_fight
      @fight = Fight.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/captain_combat_helper.rb
module CaptainCombatHelper
end

app/helpers/fighters_helper.rb
module FightersHelper
end

app/helpers/fights_helper.rb
module FightsHelper
end

app/views/captain_combat/show.html.erb
<h3>Are you ready to RUMBLEEEEEEEEEEEE ??</h3>
<p>
  Welcolm to Captain Contrat's Arena of death !! Here you'll find the best and most dangerous
  fighters of the galaxy.
  <br/>
  <br/>
  We've got them all! As you wander aroung the arena and get splatched by undread of litters (oops sorry, I meant gallons for
  our imperial system users) of blood, sweat and tears ! And tears of blood !! And blood of sweat !! One time somebody got hit by
  a tooth... In the eye... It was a canine... It almost blinded him... That poor bastard was the reason we now have to warn
  about the tears of blood...
  <br/>
  <br/>
  Anywhooooo, as I was saying : here you'll find the most dangerous fighters like the Fat Baby, the Hornless Unicorn (yup it's
  basically a horse), the Three Armed Amputed PostMan and of course the mighty one, the abyss abomination, the destroyer of dreams,
  the skull crasher, head banger, well rested MOTHER FUC***: THE FULLSTACK DEVELOPER !!
</p>

app/views/fighters/_form.html.erb
<%= form_for(fighter) do |f| %>
  <% if fighter.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(fighter.errors.count, "error") %> prohibited this fighter from being saved:</h2>

      <ul>
      <% fighter.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <p>Carefull, you can only assign 15 skills points for life, attack, dodge and critical fields</p>

  <div class="field m-t-5">
    <%= f.label :name %>
    <%= f.text_field :name, placeholder: "Enter Fighter's Name", class: "form-control" %>
  </div>

  <div class="field m-t-5">
    <%= f.label :life %>
    <%= f.number_field :life, value: @fighter.life || 0, in: 0..10, placeholder: 0, class: "form-control" %>
  </div>

  <div class="field m-t-5">
    <%= f.label :attack %>
    <%= f.number_field :attack, value: @fighter.attack || 0, in: 0..10, placeholder: 0, class: "form-control" %>
  </div>

  <div class="field m-t-5">
    <%= f.label :dodge %>
    <%= f.number_field :dodge, value: @fighter.dodge || 0, in: 0..10, placeholder: 0, class: "form-control" %>
  </div>

  <div class="field m-t-5">
    <%= f.label :critical %>
    <%= f.number_field :critical, value: @fighter.critical || 0, in: 0..10, placeholder: 0, class: "form-control" %>
  </div>

  <div class="field m-t-5">
    <%= f.label :bio %>
    <%= f.text_area :bio, placeholder: "Write about this fighter's life and accomplishments", class: "form-control" %>
  </div>

  <div class="actions">
    <%= f.submit 'A Fighter is Born!', class: "btn btn-primary m-t-15" %>
  </div>
<% end %>

app/views/fighters/edit.html.erb
<h1>Editing Fighter</h1>

<%= render 'form', fighter: @fighter %>

<%= link_to 'Show', @fighter %> |
<%= link_to 'Back', fighters_path %>

app/views/fighters/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Fighters</h1>

<table class="table">
  <thead>
    <tr>
      <th class="w-40">Name</th>
      <th class="w-10 ta-center">Life</th>
      <th class="w-10 ta-center">Attack</th>
      <th class="w-10 ta-center">Dodge %</th>
      <th class="w-10 ta-center">Crit. %</th>
      <th colspan="3" class="w-20"></th>
    </tr>
  </thead>

  <tbody>
    <% @fighters.each do |fighter| %>
      <tr>
        <td><%= fighter.name %></td>
        <td class="ta-center"><%= fighter.life %></td>
        <td class="ta-center"><%= fighter.attack %></td>
        <td class="ta-center"><%= "#{fighter.dodge * 10} %" %></td>
        <td class="ta-center"><%= "#{fighter.critical * 5} %" %></td>
        <td>
          <%= link_to fighter do %>
            <i class="zmdi zmdi-eye"></i>
          <% end %>
        </td>
        <td>
          <%= link_to edit_fighter_path(fighter) do %>
            <i class="zmdi zmdi-edit"></i>
          <% end %>
        </td>
        <td>
          <%= link_to fighter, method: :delete, data: { confirm: 'Are you sure?' } do %>
            <i class="zmdi zmdi-delete"></i>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Fighter', new_fighter_path %>

app/views/fighters/new.html.erb
<h1>New Fighter</h1>

<%= render 'form', fighter: @fighter %>

<%= link_to 'Back', fighters_path %>

app/views/fighters/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name</strong>
  <div>
    <%= @fighter.name %>
  </div>
</p>

<p>
  <strong>Life</strong>
  <div class="progress">
    <div class="progress-bar progress-bar-striped bg-danger" role="progressbar" style="width: <%= @fighter.life * 10 %>%;">
      <%= @fighter.life %>
    </div>
  </div>
</p>

<p>
  <strong>Attack</strong>
  <div class="progress">
    <div class="progress-bar progress-bar-striped bg-warning" role="progressbar" style="width: <%= @fighter.attack * 10 %>%;">
      <%= @fighter.attack %>
    </div>
  </div>
</p>

<p>
  <strong>Dodge Chances</strong>
  <div class="progress">
    <div class="progress-bar progress-bar-striped bg-success" role="progressbar" style="width: <%= @fighter.dodge * 10 %>%;">
      <%= "#{@fighter.dodge * 10} %" %>
    </div>
  </div>
</p>

<p>
  <strong>Critical Chances</strong>
  <div class="progress">
    <div class="progress-bar progress-bar-striped bg-info" role="progressbar" style="width: <%= @fighter.critical * 10 %>%;">
      <%= "#{@fighter.critical * 5} %" %>
    </div>
  </div>
</p>

<p>
  <strong>Bio:</strong>
  <div>
    <%= @fighter.bio %>
  </div>
</p>

<%= link_to 'Edit', edit_fighter_path(@fighter) %> |
<%= link_to 'Back', fighters_path %>

app/views/fights/_form.html.erb
<%= form_for(fight) do |f| %>
  <% if fight.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(fight.errors.count, "error") %> prohibited this fight from being saved:</h2>

      <ul>
      <% fight.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <label>Fighters</label>
  <div class="row">
    <div class="col-md-6">
      <%= select_tag "one[fighter_id]", options_for_select(@fighters.map {|f| [f.name, f.id]}), class: "form-control" %>
    </div>

    <div class="col-md-6">
      <%= select_tag "two[fighter_id]", options_for_select(@fighters.map {|f| [f.name, f.id]}), class: "form-control" %>
    </div>
  </div>

  <div class="actions ta-center">
    <%= f.submit 'Reaaaaaady ? Fight !!', class: "btn btn-danger m-t-15" %>
  </div>
<% end %>

app/views/fights/edit.html.erb
<h1>Editing Fight</h1>

<%= render 'form', fight: @fight %>

<%= link_to 'Show', @fight %> |
<%= link_to 'Back', fights_path %>

app/views/fights/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Fights</h1>

<table class="table">
  <thead>
    <tr>
      <th>First Fighter</th>
      <th>Second Fighter</th>
      <th>Winner</th>
      <th>Looser</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @fights.each do |f| %>
      <tr>
        <td><%= Fighter.find(f.fighter_one_id).name %></td>
        <td><%= Fighter.find(f.fighter_two_id).name %></td>
        <td><%= Fighter.find(f.winner_id).name %></td>
        <td><%= Fighter.find(f.looser_id).name %></td>
        <td>
          <%= link_to f do %>
            <i class="zmdi zmdi-eye"></i>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Fight', new_fight_path %>

app/views/fights/new.html.erb
<h1>New Fight</h1>

<%= render 'form', fight: @fight %>

<%= link_to 'Back', fights_path %>

app/views/fights/show.html.erb
<p id="notice"><%= notice %></p>

<div class="row">
  <div class="col-md-6">
    <h3>Winner</h3>
    <h4><%= @winner.name %></h4>
    <div class="progress m-t-10">
      <div class="progress-bar progress-bar-striped bg-danger" role="progressbar" style="width: <%= @winner.life * 10 %>%;">
        <%= @winner.life %>
      </div>
    </div>
    <div class="progress m-t-10">
      <div class="progress-bar progress-bar-striped bg-warning" role="progressbar" style="width: <%= @winner.attack * 10 %>%;">
        <%= @winner.attack %>
      </div>
    </div>
    <div class="progress m-t-10">
      <div class="progress-bar progress-bar-striped bg-success" role="progressbar" style="width: <%= @winner.dodge * 10 %>%;">
        <%= "#{@winner.dodge * 10} %" %>
      </div>
    </div>
    <div class="progress m-t-10">
      <div class="progress-bar progress-bar-striped bg-info" role="progressbar" style="width: <%= @winner.critical * 10 %>%;">
        <%= "#{@winner.critical * 5} %" %>
      </div>
    </div>
    <div class="ta-center">
      <%= link_to 'Show Winner', @winner %>
    </div>
  </div>

  <div class="col-md-6">
    <h3>Looser</h3>
    <h4><%= @looser.name %></h4>
    <div class="progress m-t-10">
      <div class="progress-bar progress-bar-striped bg-danger" role="progressbar" style="width: <%= @looser.life * 10 %>%;">
        <%= @looser.life %>
      </div>
    </div>
    <div class="progress m-t-10">
      <div class="progress-bar progress-bar-striped bg-warning" role="progressbar" style="width: <%= @looser.attack * 10 %>%;">
        <%= @looser.attack %>
      </div>
    </div>
    <div class="progress m-t-10">
      <div class="progress-bar progress-bar-striped bg-success" role="progressbar" style="width: <%= @looser.dodge * 10 %>%;">
        <%= "#{@looser.dodge * 10} %" %>
      </div>
    </div>
    <div class="progress m-t-10">
      <div class="progress-bar progress-bar-striped bg-info" role="progressbar" style="width: <%= @looser.critical * 10 %>%;">
        <%= "#{@looser.critical * 5} %" %>
      </div>
    </div>
    <div class="ta-center">
      <%= link_to 'Show Looser', @looser %>
    </div>
  </div>

  <div class="col-md-12 m-t-20">
    <h3>Recap:</h3>
    <div>
      <% @fight.history.split('|').each do |sentence| %>
        <%= sentence %>
        </br>
      <% end %>
    </div>
  </div>
</div>

<%= link_to 'Back', fights_path %>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-md navbar-dark bg-dark">
  <%= link_to "Captain Combat", root_path, class: "navbar-brand active" %>
  <ul class="nav navbar-nav">

    <li class="nav-item ">
      <%= link_to "Fighters", fighters_path, class: "nav-link" %>
    </li>
    <li class="nav-item">
      <%= link_to "Arena", fights_path, class: "nav-link" %>
    </li>
  </ul>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CaptainCombat</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag    'base' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/material-design-iconic-font/2.2.0/css/material-design-iconic-font.min.css">
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class="container m-t-25">
      <%= yield %>
    </div>
  </body>
</html>